name: CI
on: [push, pull_request]

jobs:
  test-all-crates:
    name: Test on Linux
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      # automatic cache for  Cargo/target
      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Sanity (see files)
        run: pwd && ls -la

      - name: Check formatting
        run: cargo fmt --all -- --check

      # Strict Clippy configuration:
      # - `all` enables standard recommended lints
      # - `pedantic` enforces additional idiomatic/style checks
      # - `nursery` enables experimental/new lints
      # - `-D warnings` turns all warnings into CI failures
      #
      # Purpose:
      # Maintain high code quality and learn idiomatic Rust patterns.
      - name: Clippy
        run: |
          cargo clippy --all-targets --all-features -- \
            -W clippy::all \
            -W clippy::pedantic \
            -W clippy::nursery \
            -D warnings

      - name: Build
        run: cargo build --all --verbose

      - name: Test
        run: cargo test --all --verbose
